import os

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 525600 # 1 year
DEFAULT_USER_PASSWORD = "Abc@123"
DEFAULT_AVATAR = "/assets/default_avatar.png"
TOKEN_URL = "/api/v1/auth/login"

config = {
    "SECRET_KEY": SECRET_KEY,
    "ALGORITHM": ALGORITHM,
    "ACCESS_TOKEN_EXPIRE_MINUTES": ACCESS_TOKEN_EXPIRE_MINUTES,
    "DEFAULT_USER_PASSWORD": DEFAULT_USER_PASSWORD,
    "DEFAULT_AVATAR": DEFAULT_AVATAR,
    "TOKEN_URL": TOKEN_URL
}